### ISSUE TITLE
GCP Director gets stuck on post-start scripts

### ISSUE THREAD

**Issue by kwiese** [pivotal-cf/credhub-release#12]
Hi, 
I'm trying to start a bosh director on gcp using the sample manifest provided, and when I run the "bosh create-env" command it completes all the way up to the "post-start scripts" where it times on connecting to the credhub server during the credhub job with the error:
```
Sending 'get_task' to the agent:
      Agent responded with error: Action Failed get_task: Task 4c2527c0-293b-4b8f-5f77-29f46cd50848 result: 1 of 2 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa. 
```

I also tried deploying the AWS director manifest, which worked fine, but I need this to work through GCP. Are there any certain settings that need to be set for GCP in order for the post-start script to work?
Thanks!

**Comment by pivotal-danjahner** [comment]
Hello - 

Have you checked the deployment logs? An easy way to do that is by running `grep -A 10 ERROR /var/vcap/sys/log/credhub/credhub.log` on the machine. The errors are often helpful, but there is a deployment [troubleshooting guide here][1] that may also be able to help.

[1]:https://github.com/pivotal-cf/credhub-release/blob/master/docs/troubleshooting-guide.md

**Comment by kwiese** [comment]
Figured it out, was an issue with an old certificate value. Thanks!!
