### ISSUE TITLE
Unable to deploy Ops Director on vSphere due to credhub failure

### ISSUE THREAD

**Issue by sumkincpp** [pivotal-cf/credhub-release#13]
We deployed Ops Manager for vSphere v1.12.2 via `pcf-vsphere-1.12.2.ova` appliance.

But after that we were unable to deploy Ops Director on vSphere due to credhub failure.
The excerpt from the log :
```
  Running the post-start scripts 'bosh/0'... Failed (00:10:10)
Failed deploying (00:20:17)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)
Deploying:
  Running the post-start script:
    Sending 'get_task' to the agent:
      Agent responded with error: Action Failed get_task: Task 063d458d-829c-479e-6967-a75b4fafdc81 result: 1 of 2 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa.
Exit code 1
===== 2017-10-20 08:38:51 UTC Finished "bosh2 --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"; Duration: 1230s; Exit Status: 1
Exited with 1.
```
The workaround mentioned on Knowledgebase page hadn't worked :
https://discuss.pivotal.io/hc/en-us/articles/115012474187-CredHub-fails-to-start-when-deploying-Pivotal-Cloud-Foundry-1-11-and-1-12-

Regenerate command for certificates had worked (200 OK), bu ut further deployment hadn't succeded.

**Comment by ebeer** [comment]
@sumkincpp can you provide the associated credhub.log file?

**Comment by sumkincpp** [comment]
@ebeer Sure! Sorry for delay, how can I get it from the VM? Where it stored and what are ssh credentials?

**Comment by sumkincpp** [comment]
Ok, seems that error is with certificates regeneration(https://docs.pivotal.io/pivotalcf/1-12/security/pcf-infrastructure/api-cert-rotation.html#regenerate).
This command succeeds :
```
$ curl "https://OPS-MAN-FQDN/api/v0/certificate_authorities/active/regenerate" \ 
-X POST \ 
-H "Authorization: Bearer YOUR-UAA-ACCESS-TOKEN" \ 
-H "Content-Type: application/json" \ 
-d '{}'
```
But further verification via 
```
curl "https://AAAAAAAAAAAA/api/v0/certificate_authorities/" -X GET -H "Authorization: Bearer XXXXXXXXX" -H "Content-Type: application/json" -k 
```
shows that only one old CA is present. 

During API call via /api/v0.certificate_authorities, the following lines appeared in /tmp/logs (Nothing unusual): [certificate_authorities regenerate.txt](https://github.com/pivotal-cf/credhub-release/files/1427712/certificate_authorities.regenerate.txt)

I believe that `Api::V0::CertificateAuthoritiesController#regenerate_certs` api call isn't regenerating CA.

**Comment by ebeer** [comment]
@sumkincpp the OpsManager certificate regeneration process is not connected to CredHub at this time, to my knowledge. Pivotal support should be able to assist you with your OpsManager issue.

**Comment by sumkincpp** [comment]
@ebeer Ok, how can I get credhub.log file from Ops Director vm?

**Comment by ebeer** [comment]
@sumkincpp for a BOSH deployment, credentials would be in the manifest and CredHub logs in /var/vcap/sys/log/credhub/  OpsManager may have a different structure, so Pivotal Support should be more helpful for your situation.

**Comment by ebeer** [comment]
@sumkincpp Did you redeploy after the rotation?

**Comment by shawnho1018** [comment]
I also encountered the same issue. Should I open a new ticket or address the issue here?

**Comment by ebeer** [comment]
Please open a new issue with the relevant logs and version information.

**Comment by sumkincpp** [comment]
As far as I remember for Pivotal installation the actual issue was with incorrect DNS entries being used.

**Comment by shawnho1018** [comment]
@sumkincpp  So..your earlier problem was a wrong DNS setting which triggers this problem? I had exact same error message like you but I cannot find credhub.log file in my OVA appliance. I even find / -name '*credhub.log*' but still cannot find it. Not sure why...
May I ask if you spot credhub.log in the folder under /var/vcap/sys/log/credhub/ ?

**Comment by sumkincpp** [comment]
@shawnho1018 It definitely wasn't there in Ops Manager cause of the failed deployment of the Ops Director
