### ISSUE TITLE
Question: credhub and AWS CloudHSM2

### ISSUE THREAD

**Issue by bpicode** [pivotal-cf/credhub-release#17]
Hi,

I have question on integration `credhub` with a HSM. If I understood [configure-luna-hsm](https://github.com/pivotal-cf/credhub-release/blob/master/docs/configure-luna-hsm.md) correctly, the docs refer to instances of [AWS CloudHSM "classic"](https://docs.aws.amazon.com/cloudhsm/classic/userguide/cloud-hsm-overview.html). My question: is it possible to run `credhub` with the [newer generation](https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html) of CloudHSMs? If so, how would one configure the BOSH manifest? A lot of the steps in [configure-luna-hsm](https://github.com/pivotal-cf/credhub-release/blob/master/docs/configure-luna-hsm.md) aren't really applicable.

Any help is appreciated. Thanks

**Comment by crawsible** [comment]
@bpicode Apologies for the delay. credhub doesn't support the newer AWS CloudHSM service. At the moment we only support integration with Luna HSMs, and AWS CloudHSM Classic instances are just Luna HSMs, hence the support.

Can I ask more about your interest in the new CloudHSM service? What makes you want to use it? Are you using CredHub yet, and if so are you integrating with Luna HSMs?

**Comment by bpicode** [comment]
Hi @crawsible,
let me quickly answer your questions by describing some key constraints:
- We wanted to issue certificates, where the issuing CA keys are stored within a HSM. Using an HSM was kind of dictated by requirements.
- Our initial line of thought saw CredHub as an intermediate layer to conveniently generate these certificates in the spirit of [Generate Credentials/Type Certificate](https://credhub-api.cfapps.io/#type-certificate30).
- I was not using CredHub before.
- The AWS CloudHSM Classic partitions are sort-of-deprecated and IIRC one cannot order them anymore.

**Comment by crawsible** [comment]
Thanks for the further information @bpicode. General PKCS#11 isn't on our roadmap in the short term, though we are working towards both AWS KMS integration, and an extension point for implementing custom encryption providers. Would the integration AWS KMS meet your needs?

**Comment by bpicode** [comment]
Probably not. For my case, the ideal solution would be some "device" that takes care of asymmetric crypto operations without ever exposing the private key to the OS/Application layer. Initially I thought that the AWS HSM was capable of that, but this was proven wrong. I don't really see how AWS KMS can help here.

**Comment by athornton2012** [comment]
@bpicode I thought that the AWS HSM support allowed you to encrypt and decrypt things without the key ever leaving the HSM. So I guess my question is: How is the private key getting to the OS/Application layer?

**Comment by johnpfield** [comment]
@bpicode @athornton2012 That's my understanding too.  The whole point of using an HSM is that the private key (or a symmetric key) never leave the hardware device.  It can't be stolen/copied, because it is never revealed to the OS/Application layer.   Instead of read key, then sign locally, the interface is "here's a buffer, sign this" and you get the result back...they private key being safe from prying eyes. 

@crawsible Curious about the lower priority of PKCS#11 support.  That standard has traditionally been the best way to add vendor-independent support for HSMs.  It's the one API that pretty much all hardware crypto devices could be expected to support...Is that no longer true?

**Comment by crawsible** [comment]
@johnpfield The cloud key management services don't have PKCS#11 interfaces -- they operate at a slightly higher abstraction layer. The cloud KMSs + Luna SafeNet Network HSMs are our initial integration targets. We chose to integrate with Luna via their libraries instead of PKCS#11 in order to take advantage of their "vHSM" failover mode of operation, which is Java library dependent.

**Comment by bpicode** [comment]
@athornton2012 @johnpfield 

> I thought that the AWS HSM support allowed you to encrypt and decrypt things without the key ever leaving the HSM.

> It can't be stolen/copied, because it is never revealed to the OS/Application layer.

That was my understanding as well. There is, however, an option to export a secret key [1]. Also I was able pull the secret key into application memory starting from a code example from the docs [2].

I want to point out that today this is not necessarily correct anymore. I noticed that the java-lib [3] is now aware if a key can be exported. Also non-exportability can be implemented by sharing a with a less privileged user [4]. Both features were introduced/documented after I opened this issue [5, 6].

[1] https://docs.aws.amazon.com/cloudhsm/latest/userguide/manage-keys.html#export-keys
[2] https://docs.aws.amazon.com/cloudhsm/latest/userguide/java-sample-sign-message.html
[3] https://docs.aws.amazon.com/cloudhsm/latest/userguide/java-lib-supported.html
[4] https://docs.aws.amazon.com/cloudhsm/latest/userguide/manage-keys.html#share-keys
[5] https://github.com/awsdocs/aws-cloudhsm-user-guide/commit/c8aafda17862986d73b2ae7281ecb5b2992b8676#diff-d54151f757a4cfdd44cf1cf9b024a850R28
[6] https://github.com/awsdocs/aws-cloudhsm-user-guide/commit/c8aafda17862986d73b2ae7281ecb5b2992b8676#diff-ad087f156baf1d87c69d6bd4a24e7272R158

**Comment by athornton2012** [comment]
@bpicode Is one of your constraints that the library you are using should not have the ability to get a key from the HSM?

It looks like AWS KMS never lets a master key leave AWS KMS unencrypted. Would this satisfy that constraint? (https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#master_keys)

**Comment by bpicode** [comment]
@athornton2012 
> Is one of your constraints that the library you are using should not have the ability to get a key from the HSM?

It's not a matter of the library for me. As I said, correctly burying a key in the HSM was introduced or documented after I looked into it. So it is likely that the HSM would fit my needs now.

> It looks like AWS KMS never lets a master key leave AWS KMS unencrypted. Would this satisfy that constraint?

If I understood KMS correctly, it targets key for symmetric crypto operations only. So, no.

**Comment by jparnala** [comment]
@bpicode We now support pluggable encryption providers. Closing, please feel free to reach out again.
