### ISSUE TITLE
Encountered credhub issue 

### ISSUE THREAD

**Issue by shawnho1018** [pivotal-cf/credhub-release#18]
I was using pcf-vsphere-2.0-build 213 to create bosh director. After the configuration, I encountered the following issue. This symptom is similar to the following ticket: https://github.com/pivotal-cf/credhub-release/issues/13

--
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Running the post-start script:
    Sending 'get_task' to the agent:
      Agent responded with error: Action Failed get_task: Task 76436801-4499-4456-600e-58d4a9082c07 result: 1 of 2 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa.

**Comment by ebeer** [comment]
What error are you seeing in the credhub.log (at /var/vcap/sys/log/credhub/)?

**Comment by shawnho1018** [comment]
This file was not generated. I only have path up to /var/vcap .

2018年1月10日 上午9:16，Edie Beer <notifications@github.com>寫道：

What error are you seeing in the credhub.log (at /var/vcap/sys/log/credhub/)?

**Comment by ebeer** [comment]
@shawnho1018 if you aren't able to access credhub or uaa logs on the director, the your best bet is to contact PCF support.

**Comment by crawsible** [comment]
Closing because this is a commercial software issue. Please reach out to Pivotal support for further assistance if necessary.
