### ISSUE TITLE
Update sample manifest for credhub/2+

### ISSUE THREAD

**Issue by amuessig** [pivotal-cf/credhub-release#28]
I think it is important to update [sample deployment manifests](https://github.com/pivotal-cf/credhub-release/tree/master/sample-manifests) for credhub/2+.
Furthermore, I think the deployment manifests should use a specific version so that you always know for which credhub version the manifest was generated.

**Comment by mdelillo** [comment]
Hi @amuessig, the [credhub-postgres-uaa manifest](https://github.com/pivotal-cf/credhub-release/blob/cb384c92b0d7e7ac869811be9be4fd43ada83916/sample-manifests/credhub-postgres-uaa.yml) is compatible with credhub 2.0. We do plan on cleaning up that directory to only have a single manifest with ops-files to change functionality.

Pinning the version of credhub in the manifest may be difficult for us to do. For example, we may add a property to the manifest before cutting a new release of credhub, in which case we wouldn't know the version number to include in the manifest. But we do guarantee that for a given tag, the sample manifest is compatible with that version of credhub.
