### ISSUE TITLE
credhub does not specify lock dependency on uaa job for bbr backup/restore

### ISSUE THREAD

**Issue by ChunyiLyu** [pivotal-cf/credhub-release#31]
### What version of the credhub server you are using?
`v.2.1.2` 
However, the issue still exist on master.

### What version of the credhub cli you are using?
No.

### If you were attempting to accomplish a task, what was it you were attempting to do?
We were running `bbr deployment restore` against a Cloud Foundry (modified environment based on PAS 2.4), and the `post-restore-unlock` script from `credhub` failed. After sshed onto the vm, we saw that the `credhub` failed to start because it cannot reach uaa, which at the time was locked by `bbr`.

The platform recovery team would recommend specify the lock dependency that `credhub` has on `uaa` in a BBR `metadata` file. Documentation can be found [here](https://docs.cloudfoundry.org/bbr/bbr-devguide.html#metadata), and here is an example showing a lock dependency on `uaa`:

```
#!/usr/bin/env bash

echo "---
backup_should_be_locked_before:
- job_name: uaa
  release: uaa
restore_should_be_locked_before:
- job_name: uaa
  release: uaa"
```

If credhub needs other components to start (like cc or routing), please include them in `metadata` file as well. 

We noticed that `credhub` can be configured without using uaa. `metadata` file can specify the lock ordering since `bbr` would ignore jobs that not present in the deployment.

### How to reproduce this issue?
This issue was never surfaced because `cloud_controller` and `uaa` were specified as lock dependencies in other jobs' `metadata`, so `bbr` always unlocked them before `credhub` and the other components. In our test, we introduce a `metadata` for the `smb` broker which specified the lock dependency on credhub, and therefore exposed this issue.

To reproduce it, we recommend running `bbr deployment restore` against a BOSH deployment that has credhub and uaa present. This issue currently does not affect `cf-deployment` or any version of PAS. `bbr deployment backup` will not reproduce this issue because `uaa` is available in read-only mode when locked during backup.

We do not understand why we have not seen this issue when we run `bbr director restore` against a PAS BOSH Director with UAA and CredHub.

### What did you expect to happen?
`credhub` post-backup-unlock and post-restore-unlock should specify lock dependency and should always succeed.

### What was the actual behavior?

Excerpt from `bbr deployment -d cf restore` logs:

```
[bbr] 2018/12/19 14:10:50 INFO - Running post-restore-unlock scripts...
[bbr] 2018/12/19 14:10:50 INFO - Unlocking cloud_controller_ng on control/020ac112-d48c-4cd8-bb28-71dcac192957...
[bbr] 2018/12/19 14:10:58 INFO - Finished unlocking cloud_controller_ng on control/020ac112-d48c-4cd8-bb28-71dcac192957.
[bbr] 2018/12/19 14:10:58 INFO - Unlocking credhub on control/020ac112-d48c-4cd8-bb28-71dcac192957...
[bbr] 2018/12/19 14:20:58 ERROR - Error unlocking credhub on control/020ac112-d48c-4cd8-bb28-71dcac192957.
[bbr] 2018/12/19 14:20:58 INFO - Unlocking uaa on control/020ac112-d48c-4cd8-bb28-71dcac192957...
[bbr] 2018/12/19 14:22:32 INFO - Finished unlocking uaa on control/020ac112-d48c-4cd8-bb28-71dcac192957.
...
1 error occurred:
error 1:
1 error occurred:
error 1:
Error attempting to run post-restore-unlock for job credhub on control/020ac112-d48c-4cd8-bb28-71dcac192957: monit: action failed -- Other action already in progress -- please try again later
monit: action failed -- Other action already in progress -- please try again later
...
```
Excerpt from `credhub.stdout.log`  logs:
```
[2018-12-19 14:17:34+0000] Could not reach the UAA server
[2018-12-19 14:18:05+0000] Could not reach the UAA server
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

Cheers,
Chunyi & @jamesjoshuahill 

cc @pivotal-cf/pcf-backup-and-restore

**Comment by ankeesler** [comment]
Thanks @ChunyiLyu - we have queued this story up for prioritization.

**Comment by joshzarrabi** [comment]
This will be out in our next minor release, thanks!
