### ISSUE TITLE
Credhub integration with new CloudHSM v2.

### ISSUE THREAD

**Issue by RamS2225** [pivotal-cf/credhub-release#40]
What version of the credhub server you are using?
1.2.0

What version of the credhub cli you are using?
2.2.1

If you were attempting to accomplish a task, what was it you were attempting to do?
We are trying to integrate Credhub with new AWS CloudHSM v2.

What did you expect to happen?
Since AWS classicHSM's are soon getting retired, We want to integrate our credhub with new cloudhsm v2.  Credhub is expected to have the below info but how do we obtain this information for new AWS cloud hsm v2?

Encryption Key Name
HSM Certificate
Partition name and password
Client certificate and private key
Partition serial numbers

What was the actual behavior?
This seem to be discussed in https://github.com/pivotal-cf/credhub-release/issues/17

And the last comment I saw was below. But couldn't find any other documentation on how to integrate credhub with new cloudhsm. 
We now support pluggable encryption providers. Closing, please feel free to reach out again.

Any guidance here would unblock couple of key projects for us.

**Comment by ankeesler** [comment]
@RamS2225 - are you looking specifically with how to integrate CredHub with a custom encryption provider? Our docs are not very good on this right now, and that is our shortcoming.

The general idea is to run a service on a UNIX domain socket that implements this gRPC contract: https://github.com/cloudfoundry-incubator/credhub/blob/2c7dffa16388b56a533b2c4d693eb1e0b6576b5b/components/encryption/src/main/proto/encryptionprovider.proto.

You will then need to pass that connection information to CredHub using these BOSH properties: https://github.com/pivotal-cf/credhub-release/blob/1c1c7f784369bf5a8f6fa9d6fc9b04b7c9ae7b8e/jobs/credhub/spec#L134-L142.

Let us know how this goes for you.

**Comment by RamS2225** [comment]
Thank you Ankeesler. All I am looking for is to store a credhub password in aws kms as part of security compliance. But it is documented nowhere how bosh syntactically supports this aws kms integration.

**Comment by RamS2225** [comment]
Your documentation is helpful. will check it out.
