### ISSUE TITLE
Credhub integration with AWS KMS

### ISSUE THREAD

**Issue by RamS2225** [pivotal-cf/credhub-release#41]
What version of the credhub server you are using?
1.2.0

What version of the credhub cli you are using?
2.2.1

If you were attempting to accomplish a task, what was it you were attempting to do?
We are trying to explore how to integrate Credhub with AWS KMS

What did you expect to happen?
Since AWS classicHSM's are soon getting retired, We want to integrate our credhub with new cloudhsm v2 or AWS KMS. 

What was the actual behavior?
There is some documentation provided here https://docs.cloudfoundry.org/credhub/kms-plugin.html But we are wondering if there are any existing templates how to integrate aws kms with bosh based credhub which we can use as an example.

Any guidance here would unblock couple of key projects for us.

**Comment by ankeesler** [comment]
@RamS2225 - I now see that these two GitHub issues are related. Apologies. Here is our example KMS plugin: https://github.com/pivotal/sample-credhub-kms-plugin. Let me know if this helps.
